### ISSUE TITLE
spike on talent.learnersguild.org

### ISSUE THREAD

**Issue by jaredatron** [LearnersGuild/talent#1]
spike on the talent.learnersguild.org

Setup the app to:
- be a single page react app
- use ReactRouter and Redux
- use a postgresql database
- use `@learnersguild/styles` for base stylesheet

## Requirements 

- webpack building one js file and one css file
- single page app with multiple (pages/urls)
- use `@learnersguild/styles` for base stylesheet

**Comment by hhhhhaaaa** [comment]
Talent is an app help  learners GET JOBS!

# Brainstorming Meeting for Talent App!

Judy, Punit, Spencer, Zubair, and Doug were at the meeting.
Michael and several others inquired and helped.

## Project Brainstorming
![img_7843](https://user-images.githubusercontent.com/6027902/31415694-dc29721c-add9-11e7-9ae2-80d6ea287a2c.JPG)

## MVP
![mvp](https://user-images.githubusercontent.com/6027902/31416064-9ad9b4aa-addb-11e7-84b8-9e6ba0e448e5.jpg)

## Design Brainstorming
![img_7847](https://user-images.githubusercontent.com/6027902/31415701-e4d72940-add9-11e7-914a-847098b65210.JPG)

## Storytime
![storytime](https://user-images.githubusercontent.com/6027902/31470115-55c8bc94-ae99-11e7-9ba7-9db9021936ff.JPG)

Talent MVP
(Minimum Viable Product)

Home/Collection List Includes...
Cursory look into Learner's Guild
List of learners
Face View
Hovering over faces shows a snippet of their information
Clicking faces links to their profile

One Individual Includes
Picture
Profile Page /w Person's Details (What Details)
Human Story/Personal Blurb
Showcase of Projects
[ ] [ ] [ ]
^ Links

Past Experience
Email
Github
LinkedIn
Twitter

Preferred Contact Information

**Comment by hhhhhaaaa** [comment]
I have pushed the framework Zubair and I made in a pull request: #10
