### ISSUE TITLE
Talent | Profile 

### ISSUE THREAD

**Issue by punitrathore** [LearnersGuild/talent#14]
- A user should be able to navigate to the learner detail page

React-Router route: `/learners/:githubHandle`

**Comment by judytuna** [comment]
![design brainstorm](https://user-images.githubusercontent.com/6027902/31415701-e4d72940-add9-11e7-914a-847098b65210.JPG)

**Comment by punitrathore** [comment]
![Uploading IMG_9959.jpg…]()

**Comment by punitrathore** [comment]
![profile-wireframe](https://user-images.githubusercontent.com/96797/31973352-4613e65c-b8da-11e7-8277-7a69091029c6.jpg)

**Comment by punitrathore** [comment]
![wireframe2](https://user-images.githubusercontent.com/96797/31973369-5ebd9ffe-b8da-11e7-87b7-1870f7a1a019.jpg)
